name: "Terraform Plan"

on:
  workflow_call:

permissions:
  checks: write
  contents: read
  id-token: write

env:
  terraform_directory: "./terraform"

jobs:
  terraform-plan:
    name: "Terraform plan"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: "eu-west-1"
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

      - name: Terraform Init
        id: init
        working-directory: ${{ env.terraform_directory }}
        run: |
          terraform init -input=false -upgrade=true

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.terraform_directory }}
        run: |
          terraform plan -input=false -lock=true -lock-timeout=30m -refresh=true